[target.aarch64-apple-darwin]
rustflags = [
    "-Cpanic=abort",
    "-lc"
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Cpanic=abort",
    "-lc"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
    "-Cpanic=abort",
    "-lc"
]
