[target.aarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tlinker.ld",
]
runner = "qemu-system-aarch64 -machine virt -cpu cortex-a57 -semihosting -nographic -kernel"

[build]
target = ["aarch64-unknown-none"]
